language: node_js
node_js:
  - '11'

os:
  - osx
  - linux
  - windows

env:
  matrix:
    - YARN_GPG=no
  global:
    secure: U98ScOVVLLQhxghbzE8O5EZA/KjqCs9X8PePney6TNqOPmVBYD8LEyi27yUCGqAxu0Q0S/1VVrfaiRjIyg3ANMD+ZeRQkEk+1rSiDod54MYLRvSwAjOIrDYUNsV48vzTPaARsL454JXa41Gkz+c5ErkE43j/HPcGJthYH6yi3U0=

filter_secrets: false

cache:
  yarn: true

branches:
  only:
    - master

script:
  - yarn
  - ./build_files/rebuild_ext
  - yarn dist
  - ./build_files/upload_package

#matrix:
#  allow_failures:
#    - os: windows
